// Generated by CoffeeScript 1.4.0
(function() {
  var Driver;

  Driver = (function() {

    function Driver() {}

    Driver.prototype.connect = function(options, cb) {};

    Driver.prototype.query = function(key, args, cb) {};

    Driver.prototype.queryOne = function(key, args, cb) {
      return this.query(key, args, function(err, rows) {
        if (err) {
          cb(err);
        }
        if ((rows != null ? rows.length : void 0) === 0) {
          return cb({
            error: 'no_rows_found'
          });
        } else {
          return cb(null, rows[0]);
        }
      });
    };

    Driver.prototype.exec = function(key, args, cb) {
      return this.query(key, args, function(err, rows) {
        if (err) {
          return cb(err);
        } else {
          return cb(null);
        }
      });
    };

    Driver.prototype.disconnect = function(cb) {};

    return Driver;

  })();

  module.exports = Driver;

}).call(this);
