// Generated by CoffeeScript 1.4.0
(function() {
  var arrayify, arrayifyOptions, escape, loglet;

  loglet = require('loglet');

  arrayifyOptions = {
    key: '?',
    merge: false
  };

  arrayify = function(stmt, args, options) {
    var key, keyVal, newStmt, outputArgs, outputSegments, seg, segments, _i, _len;
    if (options == null) {
      options = arrayifyOptions;
    }
    loglet.debug('query.arrayify', stmt, args, options);
    segments = stmt.split(/(\$\w+)/g);
    outputSegments = [];
    outputArgs = [];
    for (_i = 0, _len = segments.length; _i < _len; _i++) {
      seg = segments[_i];
      if (seg.match(/^\$/)) {
        key = seg.substring(1);
        if (!args.hasOwnProperty(key)) {
          throw {
            error: 'query.arrayify:missing_argument',
            key: key,
            args: args,
            stmt: stmt
          };
        } else if (options.merge) {
          outputSegments.push(escape(args[key]));
        } else if ((typeof options.key === 'function') || (options.key instanceof Function)) {
          keyVal = options.key();
          outputSegments.push(keyVal);
          outputArgs.push(args[key]);
        } else {
          outputSegments.push(options.key);
          outputArgs.push(args[key]);
        }
      } else {
        outputSegments.push(seg);
      }
    }
    newStmt = outputSegments.join('');
    loglet.debug('arrayify.output', newStmt, outputArgs, outputSegments);
    return [newStmt, outputArgs];
  };

  escape = function(arg) {
    if (typeof arg === 'string') {
      return "'" + arg.replace(/'/, "\\'") + "'";
    } else if (arg(intanceof(Date))) {
      return escape(arg.toString());
    } else if (arg instanceof Object) {
      throw {
        error: 'query.escape:invalid_argument',
        arg: arg
      };
    } else {
      return arg;
    }
  };

  module.exports = {
    arrayify: arrayify
  };

}).call(this);
